[Unit]
Requires=magnetowid-gluetun.service
After=magnetowid-gluetun.service
PartOf=magnetowid-gluetun.service

[Service]
NetworkNamespacePath=/run/magnetowid-gluetun/netns
BindReadOnlyPaths=/etc/magnetowid-gluetun/resolv.conf:/etc/resolv.conf
BindReadOnlyPaths=/etc/magnetowid-gluetun/nsswitch.conf:/etc/nsswitch.conf
